Feature/remove complexity and pagination constraints
multiversx/mx-sdk-nestjs pull request #98
Opened 2022-12-23 17:09 UTC by 00ssh

Removing private constraints for pagination and complexity will allow us to server more than 10000 results through Elrond API hosted instance. Since complexityThreshold is currently private, we cannot override it.

2022-12-29 10:47 UTC, gabrielmatei requested changes

2022-12-29 10:47 UTC, gabrielmatei commented on packages/common/src/interceptors/pagination.interceptor.ts
> +  constructor(readonly maxSize: number = 10000) { }
there is no need to make it public. usage example: https://github.com/ElrondNetwork/api.elrond.com/blob/92f370e8d928feb341f5f383583fa67bda571212/src/main.ts#L207

2022-12-29 10:47 UTC, gabrielmatei commented on packages/common/src/interceptors/complexity.interceptor.ts
> +  complexityThreshold: number = 10000;
it's better to make a constructor that receives `complexityThreshold` as a parameter, just like the `PaginationInterceptor`

2022-12-29 12:22 UTC, 00ssh commented on packages/common/src/interceptors/complexity.interceptor.ts
> +  complexityThreshold: number = 10000;
Thanks @gabrielmatei ! The proposed solution is simple and elegant. I've just tested in my environment with a constructor for ```ComplexityInterceptor``` and a parameter read from config.yaml in Elrond API and it works just fine.

2022-12-29 13:04 UTC, tanghel approved these changes

2022-12-29 16:15 UTC, gabrielmatei approved these changes

2023-01-05 18:46 UTC, 00ssh commented
Hi there! Is there anything else I should do for the merge?

2023-01-06 07:50 UTC, tanghel approved these changes

2023-01-06 07:50 UTC, merged